# Generated by Django 3.0.8 on 2020-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_information_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='story',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='reviewBoard/images'),
        ),
    ]
